### ISSUE TITLE
Formulário sign-in Organização - Lucas e Christian

### ISSUE THREAD

**Issue by hugohonda** [hugohonda/UnBSolidaria#11]
- [ ] editar / criar caixas de texto de acordo com entidade 'Organizacao'

- [ ] fazer validação de todos os campos do formulário
    - inserção máxima de caracteres
    - cor vermelha caso CNPJ inválido

**Comment by ChrisCWerner** [comment]
Qual o branch que devo usar?

**Comment by asm95** [comment]
E o pior que fui convidado a contribuir com o repositório e depois revogaram meu status como contribuidor. Agora devemos forkar e esperar que nossas mudanças sejam aceitas :/ Assim deve-se usar o seu fork em conjunto com sua dupla (LucasRez) e depois fazer um pull request.

**Comment by hugohonda** [comment]
Para cada issue deve ser criada um novo Branch. O @asm95 já está como colaborador no projeto, só foi alocado em outra issue (olhem nas issues, o interessante é trabalharem juntos e o colaborador sobe as modificações). Para essa issue que é do @LucasRez em dupla com o @ChrisCWerner, o Lucas tem acesso de colaborador na dupla

**Comment by lucasrezendem** [comment]
Criei a branch sign-up-organizacao

**Comment by ChrisCWerner** [comment]
Tudo feito,  só aceitar o pull request agora
#17
