### ISSUE TITLE
Preencher dados com do BD fake - Diego

### ISSUE THREAD

**Issue by hugohonda** [hugohonda/UnBSolidaria#13]
No arquivo 'BancoDeDados.java', preencher:

- [x] Voluntários com 20 valores válidos (preencher todos os campos do construtor com CPFs e outros campos válidos )
`voluntarios = Arrays.asList(
                new Voluntario(  preencher aqui os parâmetros  ),
                new Voluntario(  preencher aqui com outros parâmetros ),
                etc.
                );`
- [x] Organizações com 20 valores válidos (preencher todos os campos do construtor com CNPJs e outros campos válidos )
`organizacoes = Arrays.asList(
                new Organizacao(),
                new Organizacao(),
                etc.
                );`
- [x] Tags com 10 valores válidos (preencher todos os campos do construtor com CNPJs e outros campos válidos )
`tags = Arrays.asList(
                new Tags(),
                new Tags(),
                etc.
        );`
- [x] Oportunidades com 20 valores válidos
`oportunidades = Arrays.asList(
                new Oportunidade(),
                new Oportunidade(),
                etc.
        );`

**Comment by DiegoBrian** [comment]
Por que na entidade Tags, o atributo Id é String?

**Comment by asm95** [comment]
@DiegoBrian, deve ser porque a @auroralimin /@scartezini iriam usar o HashMap em Java para mapear uma string (ex: Saúde) a um certo objeto (no caso, poderia ser uma lista de oportunidades).
